Document: gr-ieee802
Title: Debian gr-ieee802 Manual
Author: <insert document author here>
Abstract: This manual describes what gr-ieee802 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gr-ieee802/gr-ieee802.sgml.gz

Format: postscript
Files: /usr/share/doc/gr-ieee802/gr-ieee802.ps.gz

Format: text
Files: /usr/share/doc/gr-ieee802/gr-ieee802.text.gz

Format: HTML
Index: /usr/share/doc/gr-ieee802/html/index.html
Files: /usr/share/doc/gr-ieee802/html/*.html
